"""Precedent Policy generator router (FR-08)."""
import uuid

from fastapi import APIRouter, Depends

from missionguard_api.core.security import get_current_user
from missionguard_api.schemas import PolicyGenerateRequest, PolicyGenerateResponse

router = APIRouter()


_POLICY_TEMPLATE = """\
# Gift Acceptance & Strategic Alignment Policy
**Organization ID:** {org_id}
**Risk Profile:** {risk_tolerance}
**Generated by:** MissionGuard AI v0.1 | {date}

---

## 1. Purpose
This policy ensures that all restricted gift offers are evaluated against the organization's
current strategic plan before acceptance, protecting mission integrity and preventing donor-driven
strategic drift ("tyranny of the next gift").

## 2. Scope
Applies to all gifts ≥ $10,000 USD with donor-specified restrictions on program, geography, or
staffing — or any gift that would require creating a new program or expanding to an unplanned
service area.

## 3. Evaluation Threshold
| Gift Size | Required Review |
|-----------|----------------|
| < $10k | ED discretion |
| $10k – $99k | ED + Finance Committee |
| ≥ $100k | Full Board vote (quorum required) |

## 4. Mandatory Feasibility Study
Any gift requiring expansion to a new geography or program area must be accompanied by:
- A data-driven needs assessment for the proposed area
- A 24-month cost/outcome projection
- A staffing capacity analysis for existing programs

## 5. Pilot Phase Default ({risk_tolerance} profile)
{pilot_clause}

## 6. Precedent Look-Back
Before accepting any restricted gift, the ED must review the last three years of restricted gifts
to assess precedent risk. This review must be documented and attached to the Board memo.

## 7. Annual Review
This policy is reviewed annually by the Board Ethics/Governance Committee.

---
*Generated by MissionGuard AI. Have your legal counsel review before adoption.*
"""

_PILOT_CLAUSES = {
    "protective": (
        "All out-of-strategy gifts MUST be structured as a **time-limited 12-month pilot** "
        "with pre-agreed success metrics. Full acceptance requires Board re-approval after pilot completion."
    ),
    "balanced": (
        "Out-of-strategy gifts are **strongly recommended** to be structured as an 18-month pilot "
        "with defined success criteria. The Board may waive the pilot requirement by a 2/3 majority vote."
    ),
    "growth": (
        "Pilots are **encouraged** but not mandatory when projected impact clearly exceeds risk. "
        "A written risk assessment is required and must be archived in the audit trail."
    ),
}


@router.post("", response_model=PolicyGenerateResponse)
async def generate_policy(
    body: PolicyGenerateRequest,
    _user: dict = Depends(get_current_user),
):
    """Auto-generate a Gift Acceptance & Strategic Alignment Policy (FR-08)."""
    from datetime import date

    pilot_clause = _PILOT_CLAUSES[body.risk_tolerance]
    markdown = _POLICY_TEMPLATE.format(
        org_id=body.organization_id,
        risk_tolerance=body.risk_tolerance.capitalize(),
        date=date.today().isoformat(),
        pilot_clause=pilot_clause,
    )
    return PolicyGenerateResponse(
        organization_id=body.organization_id,
        policy_markdown=markdown,
    )
